FROM node:20.17-alpine

WORKDIR /usr/src/app

COPY ["package.json", "./"]

RUN npm install --silent --production

COPY . .

ARG NODE_ENV 

ENV NODE_ENV=${NODE_ENV}

RUN npm run build

EXPOSE 7000

CMD ["node", "dist/index.js"]